### ISSUE TITLE
backslashes in docstring

### ISSUE THREAD

**Issue by mhvwerts** [rsmith-nl/latable#1]
Thank you for your `latable` code. When I try it out, I get a warning concerning an "unknown escape sequence `\e`". This is due to the backslashes in the docstring for `prepare()`, which are interpreted by Python as escape sequences. To get "normal" backslashes in the docstring output replace the simple backslashes in the docstring by double backslashes (you probably know this) .

That is,

```
(...)
    Example:
    >>> import latable
    >>> header, row, footer = latable.prepare('ll')
    >>> print(header)
    \\begin{tabular}{ll}
    >>> print(row('1', '2'))
    1 & 2\\\\
    >>> print(row(3, 4.56))
    3 & 4\\\\
    >>> print(footer)
    \\end{tabular}
```

**Comment by rsmith-nl** [comment]
Do you get the error during import?
Which version of Python are you testing with?

When I import the module in Python 3.11, it does not produce a warning.
Only when I run `make test` can I reproduce it.

**Comment by mhvwerts** [comment]
Thank you for looking into this. I think that I started receiving these warnings since updating to Python 3.12. I also get them sometimes when running some of my own scripts. They are easily fixed by using `r` raw string literals (or by replacing each `\` by `\\`, but that is more of a hassle and less readable).

It is actually a useful warning, as it indicates that one runs the risk of encoding special sequences (`\t` , `\n`, etc.) instead of just the raw string literal as (probably) intended. This can prevent bugs that can be difficult (time-consuming...) to spot (*e.g.* in communication with connected devices over a serial port, but that is a different story!)
